name = "quentinlemcode-site-cms-oauth"
main = "index.js"
compatibility_date = "2025-09-15"

[vars]
REDIRECT_URI = "https://quentinlemcode-site-cms-oauth.quentinlemcode-cloudflare.workers.dev/callback"

[observability.logs]
enabled = true
