backend:
  name: github
  repo: QuentinLemCode/quentinlemcode-site
  branch: main
  base_url: https://quentinlemcode-site-cms-oauth.quentinlemcode-cloudflare.workers.dev/
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Accueil"
        name: "accueil"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }

